version: 2

defaults: &defaults
  working_directory: ~/tmp
  docker:
    - image: circleci/node:11

only-deploy-tags: &only-deploy-tags
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
      #      - run:
      #          name: code-coverage
      #          command: 'jest src --coverage --coverageReporters=text-lcov | coveralls'
      #      - store_artifacts:
      #          path: coverage
      - store_artifacts:
          path: dist/bundles-report/index.html
          prefix: bundle-report-html

  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm run test
      - store_artifacts:
          path: coverage
#          destination: yebal

  deploy_to_npm:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test_all:
    jobs:
      - build: *only-deploy-tags
      - test
      - deploy_to_npm:
          <<: *only-deploy-tags
#          filters:
#            tags:
#              only: /.*/
          requires:
            - test
            - build
